### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by audriusrudalevicius** [qwertzui11/voxelTerrain#4]
Hello, i'm trying to compile on ubutnu with gcc

i had installed following libraries:
libbz2-dev
libboost-dev
libogre-1.9-dev
libois-dev
libboost-all-dev

I'm getting error with libboost Serialization

log: https://pastebin.com/raw/v20XCCuM

Is there any instruction for compiling?
Which version of libboost is supported?

**Comment by qwertzui11** [comment]
I fixed the compile issue, in newer versions of boost, boost::serialization seemed to have changed.
May you try to recompile?

**Comment by audriusrudalevicius** [comment]
Thanks for super fast fix, now it works
