### ISSUE TITLE
option (BLUB_BUILD_PHYSIC "build physic" ON) produce error of cmake

### ISSUE THREAD

**Issue by geotyper** [qwertzui11/voxelTerrain#5]
Try to build voxelTerrain with physics support.
But it is no example of code in examples.
And looks like support of physics removed from source code.
Can you post or send to me some additional code.

and example of importing mesh is date(old syntax)  need to use t_config in  voxel::edit::mesh<t_config>::pointer in example voxel::edit::mesh<t_voxel>::pointer 
And import makes with some artifacts (additional vertexes)

**Comment by qwertzui11** [comment]
with bullet physics: create from every `surface tile` a `bullet MeshShape` and add it to the physics world. That should do it.
So do a `PhysicsTile` just like `OgreTile`. and use it in the same fashion. https://github.com/qwertzui11/voxelTerrain/blob/master/examples/voxelterrain/source/OgreTile.hpp

**Comment by geotyper** [comment]
Thanks for prompt answer

**Comment by geotyper** [comment]
as say before, try to integrate VoxelTerrain with Bullet engine(or the same like PhysX)
Understand that module will look like OgreTile, but its too small information.
If you have some draft modules of such integration(if it with errors not problem), can you send to me by email, need some basis to step up.

**Comment by qwertzui11** [comment]
Here you go. These are the implementation files for physx and/or bullet. these should give you a good idea how voxel surface to physics works. However you still need to know how physx or bullet work.

[libblub-master-modules-physic-source-blub-physic-voxel-surface.tar.gz](https://github.com/qwertzui11/voxelTerrain/files/4022239/libblub-master-modules-physic-source-blub-physic-voxel-surface.tar.gz)
[libblub-master-modules-physic-source-blub-physic-rigid.tar.gz](https://github.com/qwertzui11/voxelTerrain/files/4022240/libblub-master-modules-physic-source-blub-physic-rigid.tar.gz)

**Comment by geotyper** [comment]
thanks a lot!
this is video of experiments https://youtu.be/dJDdS4KhtO0

**Comment by qwertzui11** [comment]
nicely done! :smile:

**Comment by geotyper** [comment]
Try to understand how this modules work (good experience to me to see that they support both bullet and physX engines)
in examples/cmakelists:
if (BLUB_BUILD_PHYSIC)
  set(EXAMPLES_TO_BUILD ${EXAMPLES_TO_BUILD} physic)  
endif (BLUB_BUILD_PHYSIC)
write an error/ if you have near you code of this example/ it save to me holidays time )

**Comment by geotyper** [comment]
and 
![image](https://user-images.githubusercontent.com/30755433/71777445-241fc480-2fb1-11ea-951a-9831a4a10e94.png)

 fatal error: blub/physic/predecl.hpp: No such file or directory
 #include "blub/physic/predecl.hpp"
![image](https://user-images.githubusercontent.com/30755433/71777472-811b7a80-2fb1-11ea-8d48-d0f1b027e050.png)
#include "blub/physic/material.hpp"
#include "blub/physic/system.hpp"
#include "blub/physic/shape/base.hpp"

#include "blub/physic/shape/mesh.hpp"

**Comment by qwertzui11** [comment]
those files shall be hints on how to implement it. those files are not ready to use implementation files

**Comment by geotyper** [comment]
But previous files highly depends on them.
And what about: set(EXAMPLES_TO_BUILD ${EXAMPLES_TO_BUILD} physic)?
this is also secret file? )
