### ISSUE TITLE
When create spheres some of them have cut sides/ and on this cuts another color then for sphere

### ISSUE THREAD

**Issue by geotyper** [qwertzui11/voxelTerrain#7]
![image](https://user-images.githubusercontent.com/30755433/71727056-24518000-2e4a-11ea-8927-44029555c9fb.png)

and it look like LOD system change color of some triangles
![image](https://user-images.githubusercontent.com/30755433/71727773-5f54b300-2e4c-11ea-8150-b1f901ccd0d6.png)

on near distance this sphere is normal colored

**Comment by qwertzui11** [comment]
more details and some source-code would be helpful to resolve this issue.

**Comment by geotyper** [comment]
take all code from example customVertexInfo
and create spheres in loop:
```
auto ss=t_customEdit::create(sphere(vector3(), 2.00));
ss.data()->diffuseToSet=colour(RandomInt(50,190)/255.0f,RandomInt(50,190)/255.0f,RandomInt(50,190)/255.0f, 1.0);
t_editSphere::pointer sphereEdit2(ss);
voxelContainer->editVoxel(sphereEdit2,transform(vector3(RandomInt(-50,50), RandomInt(-50,50), RandomInt(-50,50)),
              quaternion(), 4.));
```

**Comment by geotyper** [comment]
found why appear this artifacts, if create customedit sphere with radius 1.0(for example) and than in transform increase radius to   4(for example)/ if create with radius 4 and transform size 1.0/ artifacts disappears

**Comment by qwertzui11** [comment]
nicely done. I'd be very happy about a pull request
