### ISSUE TITLE
parametr to choose in edit/sphere

### ISSUE THREAD

**Issue by geotyper** [qwertzui11/voxelTerrain#8]
![image](https://user-images.githubusercontent.com/30755433/71745442-326bc480-2e7b-11ea-8d07-1725c642263b.png)

what logic to use 127 in clamp function? (or experimental figure)

**Comment by qwertzui11** [comment]
in the line below the value will get casted to `int8`. which can hold values in the range `[-127,127]`
clamp ensures that, that range will not get exceeded.
